export const CATEGORIAS = [
  {
    id: 1,
    slug: "modo-uruguayo",
    name: "Modo Uruguayo",
    emoji: "🇺🇾",
    color: "#f4442e",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description: "Modismos, murga, mate y quilombo. El mazo más nuestro.",
  },
  {
    id: 2,
    slug: "historia",
    name: "Historia",
    emoji: "📜",
    color: "#b5651d",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description: "Próceres, fechas patrias y hechos que todos deberían saber.",
  },
  {
    id: 3,
    slug: "geografia",
    name: "Geografía",
    emoji: "🗺️",
    color: "#0f5462",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description:
      "Países, capitales, ríos y lugares que viste una vez en un mapa.",
  },
  {
    id: 4,
    slug: "deportes",
    name: "Deportes",
    emoji: "⚽",
    color: "#2e8b57",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description: "Fútbol, básquet, rugby y todo lo que se discute en el asado.",
  },
  {
    id: 5,
    slug: "cine-y-series",
    name: "Cine y Series",
    emoji: "🎬",
    color: "#5b3a8e",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description: "Películas, actores, personajes y esa serie que todos vieron.",
  },
  {
    id: 6,
    slug: "musica",
    name: "Música",
    emoji: "🎵",
    color: "#d6336c",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description: "Bandas, cantantes, géneros y canciones pegadizas.",
  },
  {
    id: 7,
    slug: "tecnologia",
    name: "Tecnología",
    emoji: "💻",
    color: "#1aa7ec",
    textColor: "#17313b",
    indexColor: "#f4442e",
    description: "Apps, marcas, inventos y jerga de internet.",
  },
  {
    id: 8,
    slug: "comida-y-bebida",
    name: "Comida y Bebida",
    emoji: "🍔",
    color: "#f2994a",
    textColor: "#17313b",
    indexColor: "#f4442e",
    description:
      "Platos, ingredientes y esa comida que se discute en cada casa.",
  },
  {
    id: 9,
    slug: "animales",
    name: "Animales",
    emoji: "🐾",
    color: "#6b8e23",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description: "De la granja, la selva y el fondo del mar.",
  },
  {
    id: 10,
    slug: "famosos-y-personajes",
    name: "Famosos y Personajes",
    emoji: "🌟",
    color: "#ffc800",
    textColor: "#17313b",
    indexColor: "#f4442e",
    description: "De la tele, el cine, los dibujitos y la vida real.",
  },
  {
    id: 11,
    slug: "ciencia",
    name: "Ciencia",
    emoji: "🔬",
    color: "#17313b",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description:
      "Descubrimientos, inventos y cosas que aprendiste en el liceo.",
  },
  {
    id: 12,
    slug: "arte-y-literatura",
    name: "Arte y Literatura",
    emoji: "🎨",
    color: "#8e3b46",
    textColor: "#fff7e8",
    indexColor: "#ffc800",
    description: "Libros, pintores, obras y autores de toda la vida.",
  },
];

export default CATEGORIAS;
